### PR TITLE
[structure] Improve type inference from filters

### LINKED ISSUE #1567: Upgrading to 0.144 causes 'create new...' button to disappear from document pane
**Describe the bug**

The 'create new' button no longer renders on the document pane. See discussion at https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1571990263175100

**To Reproduce**

Start with a studio on 0.142, upgrade to 0.144, button disappears. See video here: https://sanity-io-land.slack.com/files/UB985R00J/FPT2NMU4V/sanity.mp4

**Expected behavior**
Expected to see the create new button.

**Screenshots**
See video above

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
@sanity/cli                0.144.0 (up to date)
@sanity/base               0.144.0 (up to date)
@sanity/color-input        0.144.0 (up to date)
@sanity/components         0.144.0 (up to date)
@sanity/core               0.144.0 (up to date)
@sanity/dashboard          0.144.0 (up to date)
@sanity/default-layout     0.144.0 (up to date)
@sanity/default-login      0.144.0 (up to date)
@sanity/desk-tool          0.144.0 (up to date)
@sanity/google-maps-input  0.144.0 (up to date)
@sanity/vision             0.144.0 (up to date)

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
6.12.0
v8.11.1

**Additional context**
I do use the structure builder, and so it could be related to my structure builder code. I'll copy that in below.

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

### PR DESCRIPTION
**Pull request by rexxars**
**Type of change (check at least one)**

- [x]  Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [ ]  Yes
- [x]  No

**Current behavior**

When you use filters for document lists such as `_type in [$foo]`, the inferring of schema type fails, which makes intent handlers fail to recognize they can handle the intent, as well as initial value templates from appearing automatically. 

**Description**

This PR picks up on  type filters using the `in` operator, and also expands to match all specified types. This enables document lists with filters such as  `_type == "foo" || _type == "bar"` to pick up initial value templates from both `foo` and  `bar`, as well as allowing both schema types to be recognized by the intent handler. 

Fixes #1567 

**Note for release**

Improve type inference for document list filters

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title includes a link to the relevant issue
- [x]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted
- [x]  The test suite is passing
- [ ]  Corresponding changes to the documentation have been made

### CODE REVIEW

File: packages/@sanity/structure/src/DocumentList.ts [hunk 1]
```diff
@@ -173,30 +176,74 @@ function inferInitialValueTemplates(
...
+  let typeNames = getTypeNamesFromEqualityFilter(filter, params)
+
+  if (typeNames.length === 0) {
+    typeNames = getTypeNamesFromInTypesFilter(filter, params)
+  }
+
+  return typeNames
+}
+
+// From _type == "movie" || _type == $otherType
```
Comment (thomax) [inline packages/@sanity/structure/src/DocumentList.ts]: I find these types of comments quite helpful in understanding what's going on 👍
