### PR TITLE
fix: ensure image tool drag handles work when both coarse + fine pointers are present

### LINKED ISSUE #4807: Crop/Hotspot modal not working
**Describe the bug**

Can't edit a hotspot or crop an image on Chrome/Windows, works fine on Chrome/Android.

**To Reproduce**

1. Go to an image field
2. Click on edit hotspot button
3. Try to move the crop/hotspot handlers

**Expected behavior**

The handlers should respond to mouse interaction.

**Screenshots**
image

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.15.0 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/vision        3.15.0 (up to date)
@sanity/webhook        2.0.0 (up to date)
sanity                3.15.0 (up to date)

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
9.2.0
v18.12.1

**Additional context**
Google Chrome 115.0.5790.171

### LINKED ISSUE #4947: Crop image prioritises touch on dual input displays
Similar to [this stack overflow issue](https://stackoverflow.com/questions/76645371/sanity-io-studio-image-cropping-and-hotspot-not-working), unable to crop images with mouse input when device has both touch screen and mouse pointer options. 

The crop interface prioritises touchscreen inputs over mouse inputs (mouse does not work).  

The bug exists in at least chrome, firefox, and edge browers and has been tested on two Microsoft Surface devices (with dual touch and mouse input).

image

### PR DESCRIPTION
**Pull request by robinpyon**
### Description

This PR fixes an issue where drag handles in the image crop tool would not correctly work on devices with both _coarse_ and _fine_ pointer support (e.g. a touchscreen laptop connected to a mouse).

This opts to use pointer events (as opposed to conditionally picking either touch or mouse events) which simplifies things a little, especially since there aren't any multi-touch requirements.

### What to review

Drag handles in the image crop tool should work as normal on devices with either coarse, fine or both coarse pointer support.

### Notes for release

Fixes an issue where the image crop tool would not work on touchscreen devices with connected pointer devices.

Fixes #4807, Fixes #4947

### CODE REVIEW

File: packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/makeDragAware.tsx [hunk 1]
```diff
@@ -28,34 +25,17 @@ export function makeDragAware(Component: 'canvas') {
...
-        document.body.removeEventListener('mouseup', this.handleDragEnd)
-        document.body.removeEventListener('mouseleave', this.handleDragCancel)
-      }
-    }
-
-    handleTouchMove = (event: TouchEvent | MouseEvent) => {
-      // Disables mobile scroll by touch
-      if (this.isDragging) {
-        event.preventDefault()
-      }
```
Comment (robinpyon) [inline packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/makeDragAware.tsx:58]: This was removed in favour of using the [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS property to prevent some (but not all) touch events from being handled by the browser.

Alternatively, we. could set this to `touch-action: none` but that would prevent pinch-zooming, which can be helpful (especially if you need help targeting those draggable nodes)

**Review by bjoerge — APPROVED** [review]
Solid!
Looks like we have a few issues related to touch handling in the image tool: #4807, #4940, #4947 – can you tell if any of these will be fixed by this PR?

File: packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/makeDragAware.tsx (hunk 1 above)
Comment (bjoerge) [reply packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/makeDragAware.tsx:58]: TIL about the touch-action, thanks for sharing! Agree we should preserve pinch-zooming.

**Comment by robinpyon** [comment]
I believe this addresses #4807 and #4947, though #4940 appears to be a separate issue

**Review by sjelfull — APPROVED** [review]
LGTM
