### PR TITLE
fix: make sure that columns in formFields are aligned to the top

### LINKED ISSUE #6917: Opening one collapsible column field causes it's neighbor to disappear because they are bottom aligned.
**Describe the bug**

If you have multiple long collapsible column fields and you open one the others disappear off the bottom of the window. 

**To Reproduce**

1. Create an object with 2 columns.
2. Fill the columns with enough data to cause the first column to run off the page when not collapsed.
3. Open column 1 and notice that column two seems to have disappeared.
4. Scroll to the bottom of column 1 and notice that column two is hiding next to the bottom of column 1. 

**Expected behavior**

The column dropdowns should be aligned to the top so when one is open the other is still visible

**Screenshots**
columns-image-01
columns-image-02
columns-image-03

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.46.0 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/ui             2.3.3 (up to date)
sanity                3.46.0 (up to date)

**What operating system are you using?**
Windows

**Which versions of Node.js / npm are you running?**

Node: 18.18.0
npm: 10.2.5

**Additional context**

### PR DESCRIPTION
**Pull request by RitaDias**
### Description

Fixes #6917 

Using       options: {columns: 2}, in the schema and opening one of the columns (potentially very long) fields would cause the fields on the right to collapse all the way down and disappear beneath the scroll

before

https://github.com/user-attachments/assets/e5fdffc0-ec8b-46bc-b7c8-c6ee99fa4509

after
image

### What to review

It's self explanatory, I don't quite understand why the styling was to the bottom to begin with as I don't think even in smaller fields it makes sense to align it to the bottom.

### Testing

N/A

### Notes for release

Using options.columns will now make sure that the fields are kept to the top and not to the bottom

### CODE REVIEW

File: dev/test-studio/schema/debug/collapsibleColumnsBug.ts [hunk 1]
```diff
@@ -0,0 +1,77 @@
+import {WarningOutlineIcon} from '@sanity/icons'
+import {defineField, defineType} from 'sanity'
+
+/**
```
Comment (jordanl17) [inline dev/test-studio/schema/debug/collapsibleColumnsBug.ts]: NIT: do you think we need to have this comment? Hopefully now the bug is resolved this can just be a good testing schema for the future? Not a big issue, just a thought

Comment (RitaDias) [reply dev/test-studio/schema/debug/collapsibleColumnsBug.ts]: Nope you're right, let me remove it

Comment (RitaDias) [reply dev/test-studio/schema/debug/collapsibleColumnsBug.ts]: wasn't super picky about this in the schemas aspects but it makes sense
