### PR TITLE
fix: positioning of reference input lists in documents (and modals / dialogs / popovers)

### LINKED ISSUE #12689: Reference picker popover list is clipped at pane top when popover flips upward in long forms
Reference selector popovers clip against the form's top boundary (the document header / sticky toolbar) when the anchor field is positioned low enough in the form that the popover has to open upward. The top portion of the results list becomes visually truncated and the user cannot scroll the list to recover the clipped items, the popover's internal scroll container behaves as if the clipped area doesn't exist.

The issue reproduces with **both** reference input styles:

- A plain `type: 'reference'` field (autocomplete popover)
- A `type: 'array'` of references with `max(1)` validation (the "Add item" → document-picker popover)

Switching from single-reference to array-of-references with `max(1)` (the commonly suggested workaround for large datasets) does **not** fix the clipping.

The clipping is much more noticeable, effectively making the picker unusable, when the dataset contains thousands of referenceable documents, because the popover's max-height is fully consumed. But the clipping is structural, not dataset-dependent: it happens any time the popover opens upward against a parent boundary with `overflow: hidden`.

**To Reproduce**

1. Create a Studio connected to a dataset with a few thousand referenceable documents (e.g., 1,000+ of a single type).
2. Define a singleton schema with at least two reference fields near the bottom of the form e.g.:

```ts
defineType({
  name: 'homepage',
  type: 'document',
  fields: [
    defineField({name: 'slot1Mode', type: 'string', options: {list: ['latest', 'curated'], layout: 'radio'}}),
    defineField({name: 'slot1', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'mix'}, {type: 'dj'}, {type: 'record'}, {type: 'news'}, {type: 'tourEvent'}]})]}),
    defineField({name: 'slot2', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'mix'}, {type: 'dj'}, {type: 'record'}, {type: 'news'}, {type: 'tourEvent'}]})], validation: (r) => r.max(1)}),
    defineField({name: 'slot3', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'mix'}, {type: 'dj'}, {type: 'record'}, {type: 'news'}, {type: 'tourEvent'}]})], validation: (r) => r.max(1)}),
  ],
})
```

3. Open the document for editing, scroll so that the final slot (e.g. `slot2`) sits in the lower half of the viewport.
4. Click **Add item** on `slot2` to open the document picker popover.
5. Observe: the popover opens upward (search input at the popover bottom, results list rising above it) and the top rows of the results list are visually cut off by the document header / pane boundary. Scrolling inside the popover does not reveal the clipped rows.

**Expected behavior**

One of:

- The popover should constrain its height to the available viewport space so no rows are clipped, OR
- The popover should render as a floating layer above the form header / pane boundary (via a portal) so it can extend the full viewport height, OR
- The popover's internal scroll container should include the clipped region so users can scroll to reach items hidden above the visible area.

**Screenshots**

Image

The `homepage` singleton is open for editing. The "Add item" picker is open on `slot2`. The popover has a "Type to search" input + "+ Create..." button anchored at the bottom. The results list (DJ documents starting with "40 Thieves", "A Mountain Of One", "Aaron FIT Siegel",, etc.) extends upward and its top rows are clipped by the document pane's top boundary, the first row visible shows only the bottom half of "40 Thieves" and the rest of the actual start-of-list is invisible.]

**Which versions of Sanity are you using?**

```
@sanity/cli (global)           6.3.2 (up to date)
@sanity/assist                 5.0.4 (latest: 6.0.4)
@sanity/icons                  3.7.4 (up to date)
@sanity/vision                 5.21.0 (up to date)
sanity                         5.21.0 (up to date)
@sanity/eslint-config-studio   5.0.2 (latest: 6.0.0)
```

**What operating system are you using?**

macOS 15.7.4 (Sequoia, build 24G517), reproduced in Chrome/Safari and the Sanity desktop dashboard on the same machine.

**Which versions of Node.js / npm are you running?**

```
npm 10.9.2
node v22.16.0
```

**Additional context**

- Dataset has ~50,000 documents; the reference field targets 5 document types (`mix`, `dj`, `record`, `news`, `tourEvent`) totaling ~19,000 selectable documents (1,048 DJs, 1,274 mixes, 16,527 artists not targeted here, 56 records, 385 news, 118 tour events).
- Workarounds attempted:
  - Converting single `reference` to `array` of references with `max(1)` validation → popover clips identically.
  - `options.filter` to scope selectable documents → reduces how many items are in the popover but doesn't address the clipping itself; affected any time the list still exceeds the available upward viewport space.
- Reproduces consistently when the field is near the bottom of a form long enough that the popover is forced to flip upward. Scrolling the form up before clicking the field (so the field sits high in the viewport and the popover opens downward) avoids the clippin, confirming the root cause is the upward-flipped popover colliding with the parent pane's top boundary.
- No console errors logged when the popover opens or when attempting to scroll the clipped region.

### PR DESCRIPTION
**Pull request by RitaDias**
### Description

Fixes #12689 and a couple of other issues that have been reported.
The problem is always this: the reference input ends up beneath areas of the studio where it shouldn't. With this boundary, that won't be the problem anymore. The reference list will occupy whatever space it has available.

I didn't merge the schema changes, some of these are already available on the test studio as is though :) 

Before:
image
image
image

After:
image
image

https://github.com/user-attachments/assets/1a1340d1-d1aa-4875-9839-7139dca11715

https://github.com/user-attachments/assets/84eb89c5-0c09-491d-94d5-6c32a0fe5369

### What to review

Tested manually to make sure that both reference list shown from the bottom and top wouldn't be negatively impacted by this change. Example (document without a scroll)
image

Did I miss anything?

### Testing

Updated tests, manually tested

### Notes for release

References in dialogs and popovers will be visible with the available space and not hide under different sections of the UI

### CODE REVIEW

File: packages/sanity/src/core/form/hooks/useReferenceAutocompletePopoverBoundary.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * @internal
+ */
+export function useReferenceAutocompletePopoverBoundary(
+  referenceElement: HTMLElement | null,
+): HTMLElement | null {
+  const {element: contextElement} = useBoundaryElement()
+
+  // Prefer the nearest `BoundaryElementProvider` element when it actually contains the reference
+  // element in the DOM (typically the document pane scroll container).
+  if (contextElement && referenceElement && contextElement.contains(referenceElement)) {
```
Comment (bjoerge) [inline packages/sanity/src/core/form/hooks/useReferenceAutocompletePopoverBoundary.ts:29]: will there ever be a case where there is a boundary/context element, but it doesn't contain the referenceElement?

**Review by bjoerge — APPROVED** [review]
LGTM, great catch! Just one question, mostly curious, not a blocker.

File: packages/sanity/src/core/form/hooks/useReferenceAutocompletePopoverBoundary.ts (hunk 1 above)
Comment (RitaDias) [reply packages/sanity/src/core/form/hooks/useReferenceAutocompletePopoverBoundary.ts:29]: Hmm after we added all of the providers across the different parts there _shouldn't be_ but in case if there are, this is more of a safe guard to make sure that nothing actively breaks _if_ it happens to be that case (before the most common would have been media library things from looking at the previous PR that introduced the concept of AUTOCOMPLETE_POPOVER_BOUNDARY).

I would prefer to keep it for peace of mind but I can also remove it if you feel like it's overindexing :)
