### PR TITLE
fix(base): ensure esm interoperability in root package reexports

### LINKED ISSUE #2680: Element type is invalid
**Describe the bug**

The `Desk` tool crashed.

Stack trace:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef(BooleanInput)`.
    at createFiberFromTypeAndProps (/static/js/vendor.bundle.js:27107:21)
    at createFiberFromElement (/static/js/vendor.bundle.js:27130:15)
    at reconcileSingleElement (/static/js/vendor.bundle.js:17375:23)
    at reconcileChildFibers (/static/js/vendor.bundle.js:17435:35)
    at reconcileChildren (/static/js/vendor.bundle.js:19904:28)
    at updateHostComponent (/static/js/vendor.bundle.js:20444:3)
    at beginWork (/static/js/vendor.bundle.js:21769:14)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3330:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3379:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3434:31)
```

Component stack:
```
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(BooleanInput))
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex2))
    in ForwardRef(Flex2) (created by ForwardRef(BooleanInput))
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card2))
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card2))
    in ForwardRef(Card2) (created by ForwardRef(BooleanInput))
    in div (created by ChangeBar)
    in div (created by ChangeBar)
    in ChangeBar (created by ChangeBarWrapper)
    in div (created by ChangeBarWrapper)
    in ChangeBarWrapper (created by CoreChangeIndicator)
    in CoreChangeIndicator (created by ContextProvidedChangeIndicator)
    in ContextProvidedChangeIndicator (created by ForwardRef(BooleanInput))
    in ForwardRef(BooleanInput) (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by ForwardRef(ObjectInputField))
    in ForwardRef(ObjectInputField) (created by ForwardRef(ObjectInput))
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Grid2))
    in ForwardRef(Grid2) (created by ForwardRef(ObjectInput))
    in ForwardRef(ObjectInput)
    in ForwardRef(ObjectInput) (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in form (created by EditForm)
    in EditForm (created by FormView)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPanel)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DocumentPanel)
    in div (created by DocumentPanel)
    in BoundaryElementProvider (created by DocumentPanel)
    in PortalProvider (created by DocumentPanel)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card2))
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card2))
    in ForwardRef(Card2) (created by DocumentPanel)
    in DocumentPanel (created by DocumentPane)
    in div (created by DocumentPane)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by EnabledChangeConnectorRoot)
    in Tracker (created by EnabledChangeConnectorRoot)
    in EnabledChangeConnectorRoot (created by DocumentPane)
    in DialogProvider (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState (created by DocumentActionShortcuts)
    in DocumentActionShortcuts (created by DocumentPane)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in PortalProvider (created by DeskToolPanes)
    in div (created by styled.div)
    in styled.div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card2))
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card2))
    in ForwardRef(Card2) (created by Styled(Component))
    in Styled(Component) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in ToastProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in ZIndexProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer
```

**To Reproduce**

Add boolean type to your schema:

```
export default {
  ...
  fields: [
    ...
    {
      title: "Foo",
      name: "foo",
      type: "boolean",
    },
    ...
  ]
}
```

**Expected behavior**

No error =)

**Which versions of Sanity are you using?**

```
@sanity/cli             2.15.0 (up to date)
@sanity/base            2.15.0 (up to date)
@sanity/color-input     2.15.0 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.15.0 (up to date)
@sanity/default-layout  2.15.0 (up to date)
@sanity/default-login   2.15.0 (up to date)
@sanity/desk-tool       2.15.0 (up to date)
@sanity/vision          2.15.0 (up to date)
```

**What operating system are you using?**

Ubuntu 20.04 LTS

**Which versions of Node.js / npm are you running?**

6.14.8
v14.15.0

### PR DESCRIPTION
**Pull request by bjoerge**
### Description
Fixes #2680

The (legacy) package export entries in `@sanity/base` have up until now been doing:
```js
module.exports = require('./<path-to-module>')
```
... this caused an issue with an internal _default_ import that got reexported this way (#2680).  For better interoperability with ESM consumers, this PR makes sure the package export entries now writes the exports to `module.exports` the same way as babel are doing when transpiling ESM => CommonJS:

```js
export * from './<path-to-module>'
export {default} from './<path-to-module>'
```

Note: I'm not exactly sure _why_ this change fixes the linked issue, but suspect is has something to do with circular imports, and that the getter approach solves it.

### Notes for release

Fixes a regression in 2.15.0 causing an error with boolean fields

### CODE REVIEW

File: packages/@sanity/base/.interopReexport.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
+/**
```
Comment (mariuslundgard) [inline packages/@sanity/base/.interopReexport.js:1]: I think this filename should be a private-style `_interopReexport.js`, and not start with `.` so as to not be a hidden file on some systems.

File: packages/@sanity/base/.interopReexport.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+ * esm/commonjs interop reexport helper
+ * this should be used instead of doing `module.exports = require('./some/file')
+ * since that doesn't work properly with esm imports from the consuming end
+ * @param moduleExports export object from the exporting module
+ * @param importedModule the imported module to be reexported
+ */
+module.exports = function interopReexport(moduleExports, importedModule) {
```
Comment (mariuslundgard) [inline packages/@sanity/base/.interopReexport.js:8]: Nitpick, but the name of the function could be `_interopReexport` to match the filename.

**Review by mariuslundgard — APPROVED** [review]
LGTM!
