### PR TITLE
fix(core): icons not showing in array fields

### LINKED ISSUE #4077: [v3] Icons aren’t pulling through in array fields
# v2

Screenshot 2023-01-11 at 14 02 23@2x

# v3

Screenshot 2023-01-11 at 14 01 41@2x

_Sanity version: 3.2.0_

### PR DESCRIPTION
**Pull request by binoy14**
### Description

Fixes icons not showing in array fields in v3

Fixes #4077  

### Notes for release

Fixes icons not showing in array fields

### CODE REVIEW

File: packages/sanity/src/core/preview/components/PreviewLoader.tsx [hunk 1]
```diff
@@ -57,16 +57,25 @@ export function PreviewLoader(
...
+    if (uploadState?.previewImage) {
+      return <img alt="The image currently being uploaded" src={uploadState.previewImage} />
+    }
+
+    if (!preview?.value?.media) {
+      return schemaType.icon
+    }
+
+    // @todo: fix `TS2769: No overload matches this call.`
+    return preview?.value?.media as any
```
Comment (binoy14) [inline packages/sanity/src/core/preview/components/PreviewLoader.tsx:70]: Not sure how to fix this type issue, weirdly it works when passing it to the component but when assigned to a variable it does not work. My guess is because `ReactNode` is a `type` composed of other types it has an issue when matching a type with the expanded out type

Comment (bjoerge) [reply packages/sanity/src/core/preview/components/PreviewLoader.tsx:70]: yeah, something weird going on with the typings here, no worries.

**Review by bjoerge — APPROVED** [review]
Awesome! LGTM!
