### PR TITLE
fix(cli): handle missing dependencies on upgrade/versions

### LINKED ISSUE #3083: sanity cli 2.24.1 upgrade command seems to be failing
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

running ```sanity upgrade``` using sanity cli 2.24.1 results in ```TypeError: Invalid Version: <missing>```

**To Reproduce**

node v 14.15.4
```sanity upgrade```
returns
```Type Error: Invalid Version: <missing>
    at new f (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:4694)
    at d (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:8327)
    at Function.m [as gt] (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:8364)
    at y (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:5354:3805)
    at Array.filter (<anonymous>)
    at Object.e.default [as action] (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:5354:685)
```
running
```npx @sanity/cli@2.32.2 upgrade```
returns 
```
✖ Resolving dependenciesinking dependencies
✖ An unexpected error occurred: "ENOTDIR: not a directory, lstat '<path to project>/studio/node_modules/react-ace/dist/react-ace.js/main.js'".
✖ Resolving dependenciesinking dependencies

Error: Command failed :(
    at ~/.npm/_npx/.../node_modules/@sanity/cli/bin/sanity-cli.js:3320:2582
    at async Object.e.default [as action] (~/.npm/_npx/.../node_modules/@sanity/cli/bin/sanity-cli.js:5042:2054)
```

**Expected behavior**

Upgrade should result in upgrade with success message and no errors

**Which versions of Sanity are you using?**

2.24.1

**What operating system are you using?**
macOS 12.1

**Which versions of Node.js / npm are you running?**
node 14.15.4
npm 7.20.3

**Additional context**

### PR DESCRIPTION
**Pull request by rexxars**
### Description

This PR fixes two issues with the `sanity upgrade` command: 

1. #3009 introduced a bug where if you are missing (eg not installed) any of the declared `@sanity` modules, the CLI would crash when running `sanity upgrade`, `sanity versions` or `sanity debug` (since these all tried to fetch the installed and latest versions of a module, and a change was made in #3009 where it returned `<missing>`, which would fail for semver utility functions). Fixed this by returning `undefined` instead, and manually using `<missing>` where we wanted to print the version number. 
2. Fixes a super obscure bug where yarn would crash when upgrading `@sanity/code-input` to the latest version, as the `react-ace` dependency has a `react-ace.min.js` file in `<= 8.x` that has in `>=9.x` turned into a _folder_ (*sigh*). More details: https://github.com/securingsincity/react-ace/issues/1048 . The workaround is pretty ugly - we check to see if the code input is scheduled for an upgrade, and if it is upgraded to a version that will include an update to `react-ace`. If so, it'll manually delete the `react-ace` dependency in `node_modules` before upgrading. 

Fixes #3083

### What to review

- That the code makes sense
- That `sanity upgrade`, `sanity versions` and `sanity debug` works as expected both with and without installed dependencies
- That `sanity upgrade` works when going from `@sanity/code-input@2.23.x` to `@sanity/code-input@2.24.x`

### Notes for release

- Fixed an issue where `sanity upgrade` would fail if `@sanity/code-input` was installed
- Fixed an issue where `sanity upgrade`, `sanity versions` and `sanity debug` would fail if running without any dependencies installed

### CODE REVIEW

File: packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js [hunk 1]
```diff
@@ -74,6 +76,9 @@ export default async function upgradeDependencies(args, context) {
     )
   }
 
+  // Yarn fails to upgrade `react-ace` in some versions, see function for details
+  maybeDeleteReactAce(nonPinned, workDir)
```
Comment (ricokahler) [inline packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js:80]: are you missing an await here?

**Review by bjoerge — APPROVED** [review]
see rico's question, otherwise lgtm

File: packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js (hunk 1 above)
Comment (rexxars) [reply packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js]: Good catch! Thanks
