### PR TITLE
fix: ERR_REQUIRE_CYCLE_MODULE on older node, and windows resolve regression

### LINKED ISSUE #11369: 4.20 broken on windows: Cannot require() ES Module
**Describe the bug**

While running `sanity deploy` I was prompted to upgrade to 4.20

Once that happened, the deploy script failed with this exception:
```
Unhandled rejection: Error [ERR_REQUIRE_CYCLE_MODULE]: Cannot require() ES Module D:\Projects\swd\node_modules\@sanity\util\lib\createSafeJsonParser.js in a cycle. (from D:\Projects\swd\node_modules\@sanity\export\src\tryParseJson.js)      
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:346:15)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1385:24)
    at Module._compile (node:internal/modules/cjs/loader:1536:5)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
```

Now every time I run the sanity cli tool, it throws this error.

**To Reproduce**

I cannot get a functioning sanity cli 4.20 on windows.

```
// deleted node_modules
// deleted package-lock.json
npm install sanity --force
npx sanity //exception
```

### PR DESCRIPTION
**Pull request by stipsan**
### Description

Fixes #11369:

- `ERR_REQUIRE_CYCLE_MODULE` on node older than `20.19.5` and `22.15`
- `Error: Unable to resolve \`sanity\` module root` errors on windows.

#### `ERR_REQUIRE_CYCLE_MODULE`

This issue happens as initial versions of `require(esm)` supporting versions of node.js had a condition where it would incorrectly throw on `import cjs => require(esm)` cycles, such as `sanity` importing `@sanity/export`: https://github.com/sanity-io/sanity/blob/806be793a76e01623472e32456d4c83b8fceab94/packages/sanity/src/_internal/cli/actions/media/exportAssetsAction.ts#L4
And `@sanity/export`, a CJS-only module, ends up `require('@sanity/util/createSafeJson')`: https://github.com/sanity-io/export/blob/4a083fbaac080d7a3406af5d2da5e6e1455f73f1/src/tryParseJson.js#L1

And thus triggering the condition in node.js. The fix is to add back the CJS export to `'@sanity/util/createSafeJson'`,  and keep it for the lifetime of `sanity@4`, we can clean it up in `sanity@5`.

#### `Error: Unable to resolve \`sanity\` module root`

This issue was caused by how `__dirname` was added in files that were changed to ESM in #11021.
When in CJS node provides `__dirname` and handles OS differences for us. But when in ESM we have to do it manually, as `import.meta.url` was designed for browsers initially where there is no linux/windows file system differences to worry about. [The `fileURLToPath` utility was built for this purpose](https://nodejs.org/api/url.html#urlfileurltopathurl-options), and in this PR it's consistently applied in the codebase (we used it already in many places) and it solves issues like `Unable to resolve sanity module root`.

### What to review

Did I miss anything?

### Testing

If the CI is green that's good, as the CLI tests now test the impacted node versions. 
I've also reproed and tested the fixes in this PR on the plugins monorepo and verified the fixes: https://github.com/sanity-io/plugins/pull/140

### Notes for release

See the description.

### CODE REVIEW

File: packages/@sanity/cli/test/shared/environment.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ const getTestId = () => {
 
   const localId = readFileSync(testIdPath, 'utf8').trim().slice(0, 5)
   const ghRunId = `${process.env.GITHUB_RUN_ID || ''}`.slice(-4)
-  const ghId = `${ghRunId}-${process.env.GITHUB_RUN_NUMBER}-${process.env.GITHUB_RUN_ATTEMPT}`
+  const ghId = `${ghRunId}-${process.env.GITHUB_RUN_NUMBER}-${process.env.GITHUB_JOB_ID || process.env.GITHUB_RUN_ATTEMPT}`
```
Comment (stipsan) [inline packages/@sanity/cli/test/shared/environment.ts:65]: @bjoerge the `GITHUB_JOB_ID` is relatively new and not well documented yet: https://github.com/actions/runner/issues/324
It serves a better purpose than `GITHUB_RUN_ATTEMPT`, as `GITHUB_RUN_ATTEMPT` is scoped as `GITHUB_RUN_NUMBER`, while `GITHUB_JOB_ID` is scoped for each run of the matrix.
Without this the workflow errors out as we now have more than one cli test running for each node major.

**Comment by bjoerge** [comment]
Fix is also available  on `sanity@next`
