### PR TITLE
fix: allow global studio base path

### LINKED ISSUE #3972: basePath not applying during sanity build
**Describe the bug**

Sanity build command doesn’t apply the basePath.

**To Reproduce**

1. Setup a Next JS site with a studio folder in the file structure.
2. Add the /studio basePath to both the sanity.cli.js and sanity.config.js.
3. Run the sanity build command and specify and output path to your /public/studio Next folder.
4. View index.html in /public/studio to observe all reference urls having /static instead of /studio/static.

**Expected behavior**

Upon running ```sanity build ../public/studio -y``` I expect the index.html file to have urls that reference my basePath /studio/static.

**Screenshots**
n/a

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.0.6 (up to date)
@sanity/vision        3.0.6 (up to date)
sanity                3.0.6 (up to date)

**What operating system are you using?**

MacOS Monterey v12.0.

**Which versions of Node.js / npm are you running?**

v16.10.0

**Additional context**

I just switched to Studio v3, with a Next site and everything else is working perfectly. The studio is isolated in a folder within the Next files. To build the site I apply the following command from my root package
``` 
"sanity:build": "cd studio && sanity build ../public/studio -y",
``` 
I have the basePath specified sanity.cli.js and sanity.config.js. Both of those files exist within the studio folder and their applications are as follows.

sanity.cli.js
```
export default defineCliConfig({
  api: {
    projectId: "",
    dataset: "production",
  },
  project: {
    basePath: "/studio",
  },
});
```

sanity.config.js
```
export default defineConfig({
  name: "default",
  title: "",
  projectId: "",
  dataset: "production",
  basePath: "/studio",
  plugins: [deskTool({ structure }), media()],
  schema: {
    types: schemaTypes,
  },
});
```

### PR DESCRIPTION
**Pull request by rexxars**
### Description

There is a `basePath` option in the CLI configuration (`project.basePath`) which is also available through an environment variable (`SANITY_STUDIO_BASEPATH`). This wasn't properly threaded through to all locations, so the built javascript bundles (and preview server) did not respect it properly.

This PR addresses two separate points:

1. Makes sure the configured base path is threaded through to the correct server/build configuration
2. Prepends the configured studio basepath (if any) to the workspace base paths

I'm slightly unsure how I feel about the second point here. I do feel like you would expect the tooling to take it into account if configured, instead of having to manually configure all your workspaces to manually include it? But theoretically we could also leave it up to the user, as we do now. It is a bit of double-configuration, however, and unless you are using an environment variable to configure it, you need to define it more than once.

One could also discuss _where_ the application of the "root path" belongs - I've currently added it to `prepareConfig`, which applies it while normalizing base paths, but theoretically this could also be done earlier in the process - but then we'd need to account for single vs multiple workspaces in several locations, which I was hoping to avoid.

Would love opinions on this! 
 
Fixes #3972

### What to review

- Code
- `sanity build` + `sanity preview` with and without a configured base path (either through `sanity.cli.ts` (`project.basePath`) or through environment variable (`SANITY_STUDIO_BASEPATH`))
- `sanity dev` with and without configured base path

It's probably easiest to review this one commit at a time, since it deals with two slightly different things (build tooling vs automatically applying base path to workspaces)

### Notes for release

- Fixes an issue where a configured studio-wide `basePath` would not be respected in build output, and workspaces would have to manually include the prefix in each workspace base path

### CODE REVIEW

**Comment by mariuslundgard** [comment]
The following does currently not work in this branch:

1. Configure `project.basePath = '/test/'` in `sanity.cli.ts`
2. Build the studio using `SANITY_STUDIO_BASEPATH="/foo/" sanity build`
3. Start the preview server `sanity start`

In this case the Studio does not render, since it's running on `/test/` but serving assets on `/foo/`.

I would expect defining a environment would override override other config.

--

PS. Would like us to have unit tests to make sure `basePath` and `SANITY_STUDIO_BASEPATH` works as intended, and doesn't unintentionally break in the future.

File: packages/sanity/src/_internal/cli/actions/build/buildAction.ts [hunk 1]
```diff
@@ -75,14 +75,24 @@ export default async function buildSanityStudio(
...
+  const basePath =
+    // Allow `sanity deploy` to override base path
+    overrides?.basePath ||
+    // Environment variables
+    process.env.SANITY_STUDIO_BASEPATH ||
+    // `sanity.cli.ts`
+    cliConfig?.project?.basePath ||
+    // Fallback
+    '/'
+
```
Comment (mariuslundgard) [inline packages/sanity/src/_internal/cli/actions/build/buildAction.ts:87]: Wondering if `??` would be a better operator than `||` here.

Let's say a user wants to reset the base path using env variable:
```sh
# This might not give the expected result, since it should be "/"
# Though we allow "" since we sanitize the value to make sure it ends with a slash
SANITY_STUDIO_BASEPATH="" sanity build
```

**Comment by mariuslundgard** [comment]
We're also building the Studio in the `sanity deploy` action. We should probably also support `SANITY_STUDIO_BASEPATH="/root/" sanity deploy`?

File: packages/@sanity/server/src/buildStaticFiles.ts [hunk 2]
```diff
@@ -160,3 +160,7 @@ async function writeWebManifest(basePath: string, destDir: string): Promise<void
     .writeFile(path.join(destDir, 'manifest.webmanifest'), content, 'utf8')
     .catch(skipIfExistsError)
 }
+
+function ensureTrailingSlash(urlPath: string) {
+  return urlPath.endsWith('/') ? urlPath : `${urlPath}/`
+}
```
Comment (mariuslundgard) [inline packages/@sanity/server/src/buildStaticFiles.ts:166]: Nitpick: move helper to separate module, .e.g `ensureTrailingSlash.ts`.

File: packages/@sanity/server/src/buildStaticFiles.ts [hunk 3]
```diff
@@ -44,12 +44,12 @@ export async function buildStaticFiles(
...
 
   debug('Writing Sanity runtime files')
-  await writeSanityRuntime({cwd, reactStrictMode: false, watch: false})
+  await writeSanityRuntime({cwd, reactStrictMode: false, watch: false, basePath})
 
   debug('Resolving vite config')
   let viteConfig = await getViteConfig({
     cwd,
-    basePath,
+    basePath: ensureTrailingSlash(basePath || '/'),
```
Comment (mariuslundgard) [inline packages/@sanity/server/src/buildStaticFiles.ts:52]: We should now make `basePath` a require option for `getViteConfig` so we are not maintaing multiple default values.

File: packages/@sanity/server/src/renderDocument.ts [hunk 4]
```diff
@@ -38,6 +38,7 @@ ${generateHelpUrl('custom-document-component')}
 `.trim()
 
 interface DocumentProps {
+  basePath?: string
```
Comment (mariuslundgard) [inline packages/@sanity/server/src/renderDocument.ts:41]: Can this be a require prop now? `basePath: string`

File: packages/sanity/src/_internal/cli/util/servers.ts [hunk 5]
```diff
@@ -77,3 +79,7 @@ function toInt(value: string | number | undefined, defaultValue: number): number
   const intVal = parseInt(`${value}`, 10)
   return Number.isFinite(intVal) ? intVal : defaultValue
 }
+
+function ensureTrailingSlash(path: string) {
```
Comment (mariuslundgard) [inline packages/sanity/src/_internal/cli/util/servers.ts:83]: Reuse same helper from `buildStaticFiles.ts`?

**Comment by OlaAlsaker** [comment]
@rexxars do you have an estimate for when this PR will be merged in? We want to self-host our Sanity Studio, but in a sub-directory. The basePath-bug makes this impossible right now 😅

**Comment by jeff-overhaul** [comment]
> @rexxars do you have an estimate for when this PR will be merged in? We want to self-host our Sanity Studio, but in a sub-directory. The basePath-bug makes this impossible right now 😅

Been anxiously checking this PR status since before Christmas as well

**Comment by rexxars** [comment]
It is likely that it will land in a release next week, but we might push out a canary release you can try before the weekend. I'll keep you updated!

**Comment by rexxars** [comment]
Feel free to try out the `next` tag of the `sanity` and `@sanity/cli` packages if you want to give this a go - it will most likely go out in a proper release early next week.
