### PR TITLE
fix(core): use `<Link>` for workspace switching

### LINKED ISSUE #10995: Workspace switcher tries iframe navigation instead of URL change in v4.12.0
I added profiles to my sanity.config.ts file. 

After adding profiles the profile switcher shows up.  However if I try to switch profiles using the drop down profile switcher I get this console error. 

chrome-error://chromewebdata/:1 Refused to display 'https://ss-web-prod.sanity.studio/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

However if I just switch the URL manually from:

https://www.sanity.io/@ofD9VF5ga/studio/bo4n46nda5nnix1zdkhtgwly/default/prod/structure

to 

https://www.sanity.io/@ofD9VF5ga/studio/bo4n46nda5nnix1zdkhtgwly/default/dev/structure

then the profile loads fine.  So it seems the profile switcher just needs to switch the url rather than loading a different iframe 

my sanity.config.ts looks like this:

`import {defineConfig} from 'sanity'
import {visionTool} from '@sanity/vision'
import {schema} from './sanity/schemas'
import {structure} from './sanity/structure'
import {deskTool} from 'sanity/desk'
import {simplerColorInput} from 'sanity-plugin-simpler-color-input'
import {table} from '@sanity/table'
import {deployButton} from './sanity/plugins/deployButton'
import {
  presentationTool,
  defineDocuments,
  defineLocations,
} from 'sanity/presentation'
import {Deploy} from './sanity/plugins/components/DeploymentButton/DeployButton'
import {RocketIcon, CodeIcon} from '@sanity/icons'

const projectId = process.env.SANITY_STUDIO_PROJECT_ID || ''
if (!projectId) {
  throw new Error('SANITY_STUDIO_PROJECT_ID environment variable is required')
}

// helper to build a workspace with all your shared plugins/settings
function makeWorkspace(
    name: 'prod' | 'dev',
    title: 'Production' | 'Development',
    dataset: 'production' | 'development',
    icon: typeof RocketIcon
) {
  return {
    name,
    title,
    basePath: `/${name}`,
    projectId: projectId as string,
    dataset: dataset as string,
    icon,
    plugins: [
      deskTool({ structure }),
      visionTool(),
      table(),
      simplerColorInput({
        defaultColorFormat: 'rgba',
        defaultColorList: [
          { label: 'Text Light', value: 'white' },
          { label: 'Text Dark', value: '#464646' },
          { label: 'Text Red', value: '#821517' },
          { label: 'Custom...', value: 'custom' },
        ],
        enableSearch: true,
      }),
      // Include presentationTool for both workspaces with same config
      presentationTool({
        previewUrl: {
          origin: 'https://sanity-visual-editing-rho.vercel.app/',
          previewMode: { enable: '/api/draft-mode/enable' },
        },
        resolve: {
          // Main Document Resolver API - resolves documents from routes
          mainDocuments: defineDocuments([
            { route: '/',                filter: `_type == "landingPage" && _id == "homepage"` },
            { route: '/landing/[slug]',  filter: `_type == "landingPage" && slug.current == $slug` },
            { route: '/[category]',      filter: `_type == "productCategory" && slug.current == $category` },
            { route: '/[category]/[product]', filter: `_type == "product" && slug.current == $product` },
          ]),
          // Locations Resolver API - defines where data is used in your application
          locations: {
            landingPage: defineLocations({
              select: { title: 'title', slug: 'slug.current', _id: '_id' },
              resolve: (doc) => ({
                locations: [
                  {
                    title: doc?.title || 'Homepage',
                    href: doc?._id === 'homepage' ? '/' : `/landing/${doc?.slug}`,
                  },
                ],
              }),
            }),
            productCategory: defineLocations({
              select: { title: 'title', slug: 'slug.current' },
              resolve: (doc) => ({
                locations: [{ title: doc?.title || 'Category', href: `/${doc?.slug}` }],
              }),
            }),
            product: defineLocations({
              select: { title: 'title', slug: 'slug.current', category: 'category->slug.current' },
              resolve: (doc) => ({
                locations: [{ title: doc?.title || 'Product', href: `/${doc?.category}/${doc?.slug}` }],
              }),
            }),
          },
        },
        allowOrigins: [
          'http://localhost:3000',
          'https://ss-web-virid.vercel.app',
          'http://localhost:3333',
          // Note: Removed ss-web-prod.sanity.studio from allowOrigins to prevent iframe navigation issues
          // The Studio URL shouldn't be in allowOrigins as it's not meant to be embedded
        ],
      }),
    ],
    tools: [Deploy()], // Re-enabled since it wasn't causing the issue
    schema,
  }
}

// Export workspaces - production first as it's the default
// Note: Workspace switcher requires proper basePath configuration and a fresh Studio deploy
export default defineConfig([
  makeWorkspace('prod', 'Production', 'production', RocketIcon),
  makeWorkspace('dev', 'Development', 'development', CodeIcon),
])
`

### PR DESCRIPTION
**Pull request by pedrobonamin**
### Description

Replaces hard navigation with soft navigation in the workspace switcher menu to fix X-Frame-Options errors when the studio is embedded in iframes.

Fixes #10995

### Testing

Manual testing recommended:
1. Open studio with multiple workspaces configured
2. Click workspace dropdown and switch between workspaces
3. Verify navigation works without page reload
4. Test in embedded iframe context (should no longer trigger X-Frame-Options error)

### Notes for release
**Do not add, it was reverted**
> Fix for workspace switcher causing X-Frame-Options errors when studio is embedded.

### CODE REVIEW

File: packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx [hunk 1]
```diff
@@ -89,14 +89,10 @@ export function WorkspaceMenuButton() {
...
                       const isSelected = workspace.name === activeWorkspace.name
 
-                      // we have a temporary need to make a hard direct link to the workspace
-                      // because of possibly shared context between workspaces. When this is resolved,
-                      // we can remove this and use setActiveWorkspace instead
                       return (
                         <MenuItem
                           key={workspace.name}
-                          as="a"
-                          href={workspace.basePath}
```
Comment (juice49) [inline packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx:99]: Have you considered keeping this as an anchor link so that folks can easily open the link in a new tab, and copy the link to share it? It ideally should be an anchor link IMO so that we do not lose the expected affordances given to a link.

The `onClick` can simply be added to enable SPA navigation in environments where JS is running (which we currently assume is always the case for Studio).

Comment (stipsan) [reply packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx:99]: Wouldn't using `<Link>` from `sanity/router` accomplish that?

Comment (pedrobonamin) [reply packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx:99]: @copilot can you change it to follow the suggestion from @stipsan ?

**Review by annez — DISMISSED** [review]
