### PR TITLE
fix(structure): thread sortOrder through preview system for viewOptions

### LINKED ISSUE #1719: Studio not passing 'viewOptions' into preview prepare() function
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Following the example to tailor the preview to the active sort order as described in the docs, Studio is not passing in `viewOptions`:
https://www.sanity.io/docs/sort-orders#conditionally-render-a-preview-based-on-current-sort-option-d040558b4093

This bug is also discussed on Slack where others are experiencing the same:
https://app.slack.com/client/T9Y440GN8/threads/thread/C9Z7RC3V1-1579984491.176500

### PR DESCRIPTION
**Pull request by annez**
## Description

Threads `sortOrder` from `DocumentListPane` through the preview system so that the `prepare()` function receives `viewOptions` with the current ordering. This allows preview components to customize their output based on how documents are sorted in the list.

**Component chain:** `DocumentListPane` → `DocumentListPaneContent` → `PaneItem` → `PaneItemPreview` → `getPreviewStateObservable` → `observeForPreview`

Closes #1719

## What to review

- `packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx` - Passes sortOrder prop
- `packages/sanity/src/structure/panes/documentList/DocumentListPaneContent.tsx` - Receives and forwards sortOrder  
- `packages/sanity/src/structure/components/paneItem/PaneItem.tsx` - Adds sortOrder to props
- `packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx` - Converts sortOrder to viewOptions
- `packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts` - Accepts and forwards viewOptions

Focus on ensuring the sortOrder is correctly transformed into viewOptions format and passed to `observeForPreview`.

## Testing

Added unit tests in `packages/sanity/src/core/preview/utils/getPreviewStateObservable.test.ts`:
- viewOptions reaches `observeForPreview` with correct sort order
- Different orderings produce different viewOptions
- No sortOrder = no viewOptions (backwards compatibility)
- Multi-field orderings handled correctly

Manual verification: Document list pane with custom sort order passes ordering to prepare().

## Notes for release

**What changed:** Preview components can now access the current sort order via `viewOptions` in their `prepare()` function.

**How it affects users:** Schema authors can now customize preview output based on how documents are sorted in list views. For example, showing different fields when sorted by date vs. title.

**Example usage in schema:**
```js
preview: {
  prepare(value, viewOptions) {
    const sortedByDate = viewOptions?.ordering?.some(o => o.field === 'publishedAt')
    return {
      title: value.title,
      subtitle: sortedByDate ? value.publishedAt : value.author
    }
  }
}
```

**Limitations:** Only available in document list panes, not in reference selectors or other preview contexts.

### CODE REVIEW

File: packages/sanity/src/structure/components/paneItem/PaneItem.tsx [hunk 1]
```diff
@@ -32,12 +32,18 @@ import {MissingSchemaType} from '../MissingSchemaType'
 import {usePaneRouter} from '../paneRouter'
 import {PaneItemPreview} from './PaneItemPreview'
 
+/** Sort order information for preview viewOptions. Compatible with SortOrdering. */
+interface SortOrderInfo {
```
Comment (jordanl17) [inline packages/sanity/src/structure/components/paneItem/PaneItem.tsx]: This type already exists in `packages/@sanity/types/src/schema/types.ts` as `Pick<SortOrdering, 'by'>`. Think it best we reuse as duplicating this new type def here and in `PaneItemPreview` is unnecessary

**Review by jordanl17 — CHANGES_REQUESTED** [review]
Looking good, just think the type needs tidying
