### PR TITLE
fix: missing types in `sanity/structure` and `sanity/presentation`

### LINKED ISSUE #12079: Types for built-in plugins (structureTool, presentationTool) have gone missing
Starting from v5.3.0, the generated types for the structureTool and presentationTool are missing, and instead they are exported as `any`. This causes TS errors in my sanity config.

**Screenshots**
This is `lib/structure.d.ts` on NPM for v5.2.0:

Image

And here is the same for v5.3.0:

Image

### PR DESCRIPTION
**Pull request by stipsan**
### Description

Fixes #12079

The regression happened in #11746, released in 5.3.0.

[Checking the diff shows these entry points that got types replaced with `any`](https://npmdiff.dev/sanity/5.2.0/5.3.0/):

[lib/structure.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/structure.d.ts)
image

image
image

[lib/router.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/router.d.ts/)
image

[lib/presentation.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/presentation.d.ts/)

image

[lib/index.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/index.d.ts/)

image

[lib/desk.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/desk.d.ts/)

image
image

[lib/_singletons.d.ts](https://npmdiff.dev/sanity/5.2.0/5.3.0/package/lib/_singletons.d.ts/)

image
image
There are 100 other cases that I've omitted here.

### What to review

Did I miss anything?

### Testing

There is a pkg.pr.new link on the PR you can use to test and make sure that `import {presentationTool} from 'sanity/presentation'`, `import {structureTool} from 'sanity/structure'` and such has types instead of `any`.

### Notes for release

`sanity@5.3.0` had a regression where `structureTool()`, `presentationTool()` and a few other APIs ended up with `any` as their type, instead of the rich typescript typings that they're supposed to have. In this release the types are back 😮‍💨

### CODE REVIEW

File: packages/sanity/src/core/schema/createSchema.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import {inferFromSchema as inferValidation} from '../validation'
 
 const isError = (problem: SchemaValidationResult) => problem.severity === 'error'
 
-export const builtinSchema = SchemaBuilder.compile({
+export const builtinSchema: Schema = SchemaBuilder.compile({
```
Comment (stipsan) [inline packages/sanity/src/core/schema/createSchema.ts:9]: Needed to fix a build issue

File: packages/sanity/tsconfig.lib.json [hunk 2]
```diff
@@ -12,5 +12,8 @@
     "./src/**/*.test-d.ts",
     "./src/**/*.test-d.tsx",
     "./src/**/vitest.config.mts"
-  ]
+  ],
+  "compilerOptions": {
+    "customConditions": ["monorepo"]
+  }
```
Comment (stipsan) [inline packages/sanity/tsconfig.lib.json:18]: Will dive in the deep end in a follow up to find out exactly why typegen fails if we don't use the source conditions here for dts gen, my hunch is that it's something to do with how we mix relative and public export entrypoints in the source codebase 🤔
