### PR TITLE
fix: allow custom object types as portable text annotations

### LINKED ISSUE #3782: [v3] Annotations Error if element is added
I had to rewrite this bc, I didn't properly narrow down the issue.

Ran into an issue where if I add a custom object type in my annotations array, I get an error. However, if it's empty or if I wrap it in another object, then it's “fine” – I could be missing something?

**Steps to reproduce the behavior:**

```ts
// ./schemas/custom/richText.ts
export const richTextBasic = {
    title: 'Rich Text', 
    name: 'richTextBasic', 
    type: 'array',

    of: [{ 
        type: 'block',
        marks: {
            decorators: [
                { title: 'Emphasis', value: 'em' },
                { title: 'Strong', value: 'strong' }
            ],
            annotations: [
                { title: 'CTA', name: 'cta', type: 'cta' } // <- ERROR
            ]
        },
    }],
}
```

**Expected behavior**

It should allow me to directly add this, right?

**Screenshot**

Wrapping it in an object clears the error below
Screen Shot 2022-10-22 at 3 33 59 PM

Screen Shot 2022-10-22 at 3 36 39 PM

**Which versions of Sanity are you using?**

```bash
@sanity/cli                   2.33.3 (latest: 2.35.0)
@sanity/eslint-config-studio   2.0.0 (up to date)
```

**What operating system are you using?**

macOS Monterey Version 12.6
MacBook Pro (13-inch, M1, 2020)

**Which versions of Node.js / npm are you running?**

Node: 16.15.0
PNPM: 7.1.2

### PR DESCRIPTION
**Pull request by RitaDias**
### Description

Fixes #3782, where the validation was being too trigger happy about using custom types

The fix detects that custom types like ctaAnnotation are still placeholders ({}) during the initial validation pass and stops it from going into the isJSONTypeOf too early triggering an error before it should.

Let me know if this feels still too broad.

Schema that would break: https://github.com/sanity-io/sanity/pull/11893/changes#diff-246ea298ea0dd7e3a0922756908f7af2bdfe6cc1a4c0ce6bf3bf3fb00a8cbbf1R81-R161

Before
image

After

https://github.com/user-attachments/assets/7d8ddc17-137a-4d44-8c8e-57b91dfd08ec

### What to review

Let me know if this feels still too broad. 
Tagging @rexxars  specifically since the git blame throws it your way and I would just feel safer if other folks that have been in this area in recent times (if 7 years can be considered "recent" see something that I did not)

### Testing

Added unit tests.

You can manually test by going to the specific doc type created and either use one of the existing docs or creating an ew one [here](https://test-studio-git-fixes-3782.sanity.dev/test/structure/input-debug;annotationCustomTypeTest)

### Notes for release

Fixes bug where using custom types directly in annotations within a portable text editor would cause the studio to crash

### CODE REVIEW

File: dev/test-studio/schema/debug/annotationCustomTypeTest.ts [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+                type: 'ctaAnnotation',
+                name: 'cta',
+                title: 'CTA Link',
+              },
+              // Using a custom type directly by name - should now work!
+              {
+                type: 'tooltipAnnotation',
+                name: 'tooltip',
+                title: 'Tooltip',
+              },
```
Comment (rexxars) [inline dev/test-studio/schema/debug/annotationCustomTypeTest.ts:114]: The way these are set up would (in a regular sanity schema, not sure if PTE acts the same) create a "new" type with the name "tooltip" - eg in the resulting content you'd get `{_type: 'tooltip'}`.

While that's _valid_, it also seems unnecessary: what happens if you simply reference a type instead of giving it a name+title?

```suggestion
              // Using a custom type without aliasing - should now work!
              {
                type: 'tooltipAnnotation',
              },
```

Does this work? Eg does the PTE still give you the annotation, and do you end up with `{type: 'tooltipAnnotation'}` in the resulting output?

**Comment by RitaDias** [comment]
> I'm confused as to why the validation still works, as it appears to me that it'll just skip validation if the type isn't resolved… Does it do multiple passes? The test suite seems to suggest that it works, so I won't block - but I'm confused.

I was confused by this as well, it does look like the validation does multiple passes though the root aspect of this I didn't particularly investigate for this issue. I think it's ok to merge it and we can return to it if something starts acting off for one reason or another. Thanks for looking into it Espen!

And thanks Jordan 🙏
