### PR TITLE
fix(i18n): allow list formatter without arguments in `Translate` component

### LINKED ISSUE #6003: The structure tool crashed: Error: Interpolations with formatters are not supported when using <Translate>. Found "orphanedMarks, list".
**Describe the bug**

When opening a document in our studio, the structure tool crashes with the following error:

```
Error: Interpolations with formatters are not supported when using <Translate>. Found "orphanedMarks, list". Utilize "useTranslation" instead, or format the values passed to <Translate> ahead of time.
    at parseInterpolation (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-7MHBMVVV.js?v=cbba9afa:79789:11)
    at textTokenWithInterpolation (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-7MHBMVVV.js?v=cbba9afa:79778:18)
    at simpleParser (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-7MHBMVVV.js?v=cbba9afa:79743:27)
    at http://localhost:3333/node_modules/.sanity/vite/deps/chunk-7MHBMVVV.js?v=cbba9afa:79817:53
    at mountMemo (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-QWO7VWAV.js?v=cbba9afa:17050:27)
    at Object.useMemo (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-QWO7VWAV.js?v=cbba9afa:17374:24)
    at useMemo (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-LD72NT7V.js?v=cbba9afa:1094:29)
    at Translate (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-7MHBMVVV.js?v=cbba9afa:79817:46)
    at renderWithHooks (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-QWO7VWAV.js?v=cbba9afa:16404:26)
    at mountIndeterminateComponent (http://localhost:3333/node_modules/.sanity/vite/deps/chunk-QWO7VWAV.js?v=cbba9afa:19154:21)
```

**To Reproduce**

N/A as our studio is not public, and I don't know what in the document is causing Sanity to crash.

**Expected behavior**

The structure tool should not crash.

**Screenshots**
5kZwm4Tf@2x

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.34.0 (up to date)
@sanity/cli                 3.34.0 (up to date)
@sanity/code-input           4.1.3 (up to date)
@sanity/preview-url-secret   1.6.4 (up to date)
@sanity/ui                  2.0.10 (up to date)
@sanity/vision              3.34.0 (up to date)
sanity                      3.34.0 (up to date)
```

**What operating system are you using?**

macOS 14.3.1

**Which versions of Node.js / npm are you running?**

```
pnpm 8.8.0
node 20.10.0
```

### PR DESCRIPTION
**Pull request by rexxars**
### Description

It seems we [used a formatter](https://github.com/sanity-io/sanity/issues/6003) in a resource passed to `<Translate>`, which won't work as the "simple parser" does not reimplement all the logic from i18next. I initially did an approach where I changed the key to not use a formatter, but it quickly got a bit messy to think about whether the key should be a _new_ key, and how to reason about old versions of it.

Instead, I chose to implement _partial_ support for formatters inside of the `Translate` component - currently only for the `list` formatter, and only without arguments. In time we can see if we can expand on this, but this fixes #6003 and moves us a bit forward at least.

### What to review

- Code makes sense
- There aren't any regressions in how this works

### Testing

- Added tests for both parser and for the Translate function

### Notes for release

- Fixed an issue where the studio might crash on "orphaned marks" in the Portable Text Editor

### CODE REVIEW

File: packages/sanity/src/core/i18n/Translate.tsx [hunk 1]
```diff
@@ -106,33 +109,43 @@ export function Translate(props: TranslationProps) {
   })
 
   const tokens = useMemo(() => simpleParser(translated), [translated])
-  return <>{render(tokens, props.values, props.components || {})}</>
+  const listFormat = useListFormat()
+  const formatters: FormatterFns = {
+    list: (listValues: Iterable<string>) => listFormat.format(listValues),
```
Comment (juice49) [inline packages/sanity/src/core/i18n/Translate.tsx:114]: It's very inconsequential, but the `listValues` parameter type is redundant here. It's known from the `FormatterFns` type.

```suggestion
    list: (listValues) => listFormat.format(listValues),
```

**Review by juice49 — APPROVED** [review]
Looks great!
