### PR TITLE
fix(core): changing workspace with same document id causes error

### LINKED ISSUE #3992: Bug when switching workspaces in Studio
Hi, 

I'm having quite a big issue and can't understand why. 
I have a studio with 2 datasets : staging & production. I created a workspaces for each one of them with the following config : 

```
export default defineConfig([
	{
		name: "production",
		title: "Coucool - Public",
		icon: () => <RocketIcon onResize={undefined} onResizeCapture={undefined} />,
		projectId: "PROJECT_ID",
		dataset: "production",
		basePath: "/production",
		subtitle: "production",
		plugins: [sharedConfig()],
	},
	{
		name: "staging",
		title: "Coucool - Test",
		icon: () => <UserIcon onResize={undefined} onResizeCapture={undefined} />,
		projectId: "PROJECT_ID",
		dataset: "staging",
		basePath: "/staging",
		subtitle: "staging",
		plugins: [sharedConfig()],
	},
]);
```

<details>
  <summary>Click here to see the sharedConfig code </summary>

```
const sharedConfig = definePlugin({
	name: "sharedConfig",
	document: {
		actions: (prev, context) => {
			return context.schemaType === "siteSettings"
				? [
						...prev.filter(
							(originalAction) =>
								originalAction.action !== "delete" && originalAction.action !== "duplicate"
						),
				  ]
				: prev;
		},
	},
	plugins: [
		colorInput(),
		deskTool({
			structure: (S, context) =>
				S.list()
					.title("Contenu")
					.items([
						S.listItem()
							.title("Paramètres événement")
							.child(S.document().schemaType("siteSettings").documentId("siteSettings"))
							.icon(CogIcon),
						orderableDocumentListDeskItem({
							type: "section",
							S,
							context,
							title: "Sections",
							icon: () => <MasterDetailIcon onResize={undefined} onResizeCapture={undefined} />,
						}),
					]),
		}),
		visionTool(),
	],
	schema: {
		types: schemaTypes,
	},
});
```
</details>

The issue is that everytime I'm switching from one workspaces to another, it's like the content on the studio isn't updating (the URL is correctly updating btw) which leads to big errors. I'm also having this error snackbar everytime : 
Capture d’écran 2022-12-19 à 00 51 47

1. Create a new project
2. Add the same config that I sent you above
3. Try to switch workspaces

**Expected behavior**

When I switch workspaces, I should see the refreshed content and no error snackbar.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)             3.0.6 (up to date)
@sanity/color-input              3.0.1 (up to date)
@sanity/eslint-config-studio     2.0.1 (up to date)
@sanity/icons                    2.1.0 (up to date)
@sanity/orderable-document-list  1.0.2 (up to date)
@sanity/ui                       1.0.1 (latest: 1.0.2)
@sanity/vision                   3.0.6 (up to date)
sanity                           3.0.6 (up to date)
```

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

`nom -v: 8.19.2 / node -v: v18.12.1`

Thanks a lot

### PR DESCRIPTION
**Pull request by binoy14**
### Description

Fixes issue where switching workspaces and navigating to document that shares the same id causes an error and didn't show document history

Fixes #3992

### What to review

1. Fix issue where the memoizedPair did not account for sanity client config changing
2. Fix multiple levels of memoization for the `remoteSnapshots`

### Notes for release

- Fix issue when changing workspaces on documents that have same id didn't show document history

### CODE REVIEW

File: packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts [hunk 1]
```diff
@@ -15,5 +15,11 @@ export const memoizedPair: (
       subscriber.next(checkoutPair(client, idPair))
     }).pipe(publishReplay(1), refCount())
   },
-  (_client, idPair) => idPair.publishedId
+  (client: SanityClient, idPair: IdPair, typeName?: string) => {
+    const config = client.config()
+
+    return `${config.dataset ?? ''}-${config.projectId ?? ''}-${idPair.publishedId}-${
```
Comment (bjoerge) [inline packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts:21]: Passing a client without dataset/projectId here will probably cause problems down the line, so I'm wondering if it makes sense to throw an error here instead if that's the case. WDYT?

File: packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts [hunk 2]
```diff
@@ -15,5 +15,11 @@ export const memoizedPair: (
...
+      typeName ?? ''
```
Comment (bjoerge) [inline packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts:22]: I might be missing something, but since IDs are always unique and two documents of different types can't share the same ID, I'm not sure if we need to have `typeName` as part of the key here?

File: packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts [hunk 3]
```diff
@@ -1,16 +1,17 @@
...
 /** @internal */
-export const remoteSnapshots = memoize(
-  (client: SanityClient, idPair: IdPair, typeName: string) => {
-    return memoizedPair(client, idPair, typeName).pipe(
-      switchMap(({published, draft}) => merge(published.remoteSnapshot$, draft.remoteSnapshot$))
-    )
-  },
-  (_client, idPair, typeName) => idPair.publishedId + typeName
-)
+export const remoteSnapshots = (
```
Comment (bjoerge) [inline packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts:9]: We still need the memoize wrapper here, and it should use the same key generator as memoizedPair. 

Although removing memoization here will still benefit from using the memoized observable returned from `memoizedPair`, it will now make `remoteSnapshot` return a new observable instance every time it's called, which might break some expectations down the line.

**Review by bjoerge — CHANGES_REQUESTED** [review]
Great find and proposed fix!

I think there's a couple of minor issues that needs to be sorted before merge, see my comments.

File: packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts (hunk 2 above)
Comment (rexxars) [reply packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts:22]: A document can be deleted and recreated with a different type. Would this create problems? I feel like its safer to include the typename.

Comment (bjoerge) [reply packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts]: Ah, good point, and that's something that happens when people run migration scripts renaming types, so not that rare either. Talked with @binoy14 yesterday and it seems like it's straightforward to make `typeName` required, so we will use it as part of the cache key from now on. Thanks!
