### PR TITLE
fix(types): correct BlockRule value type from any[] to PortableTextBlock

### LINKED ISSUE #4464: Why is `block` typed as `any[]`?
I understand that the `block` type must exist within an array. However, why is it directly typed as `any[]`? Shouldn't it be typed as `any` (or better yet, `PortableTextBlock`). I'm seeing [the tests](https://github.com/sanity-io/sanity/blob/v3.10.0/packages/%40sanity/types/src/schema/test/block.test.ts#L18) showing that initialValue and validation expect an array, but the array type should be expecting that, not the block. Am I misunderstanding this?

### PR DESCRIPTION
**Pull request by jordanl17**
### Description
Fixes #4464. 

`BlockRule` and `BlockDefinition` used `any[]` as their value type, but a block's runtime value is a single `PortableTextBlock` object - not an array. Every other schema type (`StringRule`, `NumberRule`, `ObjectRule`) uses its correct singular value type. This change makes block consistent.

### Backwards compatibility

This is a type-level breaking change by strict semver standards: `custom()` validators on block types will now receive `PortableTextBlock` instead of `any[]`. In practice, the risk is low:

- The `any[]` type was wrong - it never matched the runtime value. Anyone calling array methods based on this type already had a latent runtime bug.
- any is maximally permissive, so most real-world validators access object properties on value rather than treating it as an array. That code continues to work.
- The test that accompanied the original typing used `value?.filter(...)` as if it were an array - confirming the type was incorrect, not that array usage was intended.

### What to review
- `BlockRule` now `extends RuleDef<BlockRule, PortableTextBlock>` instead of `RuleDef<BlockRule, any[]>`
- `BlockDefinition.initialValue` and `BlockDefinition.validation` use `PortableTextBlock` instead of `any[]`
- Promoted `PortableTextBlock` and its constituent types (`PortableTextTextBlock`, `PortableTextObject`, `PortableTextSpan`, `PortableTextChild`, `PortableTextListBlock`) from `@alpha` to `@public` - these types have been stable since September 2020 and are already widely used by consumers

### Notes for release
`BlockRule` now uses `PortableTextBlock` instead of `any[]`, matching the actual runtime value passed to custom validators.

### CODE REVIEW

File: packages/@sanity/types/src/schema/definition/type/block.ts [hunk 1]
```diff
@@ -259,7 +260,7 @@ export interface BlockDefinition extends BaseSchemaDefinition {
   lists?: BlockListDefinition[]
   marks?: BlockMarksDefinition
   of?: ArrayOfType<'object' | 'reference'>[]
-  initialValue?: InitialValueProperty<any, any[]>
+  initialValue?: InitialValueProperty<any, PortableTextBlock>
```
Comment (pedrobonamin) [inline packages/@sanity/types/src/schema/definition/type/block.ts]: The changes make sense, but is this actually valid?
I tried it and we surface an error when adding an initial value to the block definition.
I added this in `AllTheBellsAndWhistles` 

```diff
        defineArrayMember({
          type: 'block',
          name: 'block',
          title: 'Block',

+          initialValue: {
+           style: 'normal',
+            _type: 'block',
+           _key: '123',
+           children: [
+              {
+                _type: 'span',
+                text: 'Hello, world!',
+              },
+            ],
+          },

```

Typescript validates it, but then the studio opens with an error:

Image


````
# Schema errors

There were errors while attempting to compile the configuration of your Sanity Studio Schema types.

## Document type "pt_allTheBellsAndWhistles"

Path: pt_allTheBellsAndWhistles:document → fields → text:array → of → block:block
Error: Found unknown properties for block declaration: "initialValue"

## Document type "pt_allTheBellsAndWhistles"

Path: pt_allTheBellsAndWhistles:document → fields → text:array → of → block:block
Error: Found unknown properties for block declaration: "initialValue"

```

Comment (jordanl17) [reply packages/@sanity/types/src/schema/definition/type/block.ts]: Good catch! You're right - `initialValue` on blocks passes TypeScript but the runtime schema validation rejects it (it's not in the block allowlist).

I've added a fix now where `BlockDefinition` now overrides `initialValue` with `never`, so TypeScript rejects it through `defineType`, `defineField`, and `defineArrayMember`

A couple of things to note:

Inline `array.of` usage without `defineArrayMember` (e.g. `of: [{type: 'block', initialValue: ...}]`) still accepts it. The `of` array resolves to a union of all intrinsic types, and if any member allows `initialValue`, they all do. Fixing that would mean restructuring the `ArrayOfType` discriminated union, which is well beyond this PR's scope.

This is also a stricter type for consumers. If anyone already has `initialValue` on a block definition, they'll get a new TypeScript error after upgrading. But their code was already broken at runtime - the studio throws a schema validation error at startup. We're just surfacing that failure earlier, at compile time instead of runtime.

**Review by pedrobonamin — APPROVED** [review]
Looks good to me!

File: packages/@sanity/types/src/schema/definition/type/block.ts (hunk 1 above)
Comment (pedrobonamin) [reply packages/@sanity/types/src/schema/definition/type/block.ts]: Great, thank you!!
