### PR TITLE
fix(cli): patch missing `SYSTEMROOT` env var on windows

### LINKED ISSUE #4194: I have an account but still seeing this error
? Login type GitHub
Opening browser at https://api.sanity.io/v1/auth/login/github?type=listen&uuid=a912a197d93723af3be6e3f554f62a79&source=cli&label=octseven+%2F+win32
⠋ Waiting for browser login to complete... Press Ctrl + C to cancelnode:events:491
      throw er; // Unhandled 'error' event
      ^
Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
PS C:\Users\hp\Desktop\Sanity\backend> npm create sanity@latest -- --template clean --create-project "Sanity Project" --dataset production
You're setting up a new project!
We'll make sure you have an account with [Sanity.io](http://sanity.io/). Then we'll
install an open-source JS content editor that connects to
the real-time hosted API on [Sanity.io](http://sanity.io/). Hang on.
Press ctrl + C at any time to quit.
Prefer web interfaces to terminals?
You can also set up best practice Sanity projects with
your favorite frontends on https://www.sanity.io/templates
We can't find any auth credentials in your Sanity config
- log in or create a new account

### LINKED ISSUE #4195: First time setup/signup failing
**Issue** 

Setting up the sanity backend for the very first time following an online tutorial - used the following command for the same:
`npm create sanity@latest -- --coupon javascriptmastery2022` but the browser window does not open and the cli is getting terminated with the below error stack trace:

⠋ Waiting for browser login to complete... Press Ctrl + C to cancelnode:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBoAHQAdABwAHMAOgAvAC8AYQBwAGkALgBzAGEAbgBpAHQAeQAuAGkAbwAvAHYAMQAvAGEAdQB0AGgALwBsAG8AZwBpAG4ALwBzAGEAbgBpAHQAeQA/AHQAeQBwAGUAPQBsAGkAcwB0AGUAbgAmAHUAdQBpAGQAPQA4AGEANwAwADgAYQA0ADgANQAxAGEAMQAxAGYAOAA0ADgAMQAwAGYANQBjADQAYwA2ADAAZgA3AGUAMwBjADUAJgBzAG8AdQByAGMAZQA9AGMAbABpACYAbABhAGIAZQBsAD0AUwBoAHIAZQB5AGEAbgBzAE0AUwBJACsAJQAyAEYAKwB3AGkAbgAzADIAIgA='
  ]
}

Node.js v17.6.0

**To Reproduce**

1. create a folder 
2. run command `npm create sanity@latest -- --coupon javascriptmastery2022` or even without the coupon flag
3. once you select the preferred login method and hit enter, you should see the above error stack trace.

**Expected behavior**

The browser window should open to complete the signup process while the cli waits

**Which versions of Sanity are you using?**
Getting below error when running `sanity versions`:
sanity : File C:\Users\xxxx\AppData\Roaming\npm\sanity.ps1 cannot be loaded. The file C:\Users\xxxx\AppData\Roaming\npm\sanity.ps1 is not digitally signed. You 
cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ sanity versions
+ ~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**What operating system are you using?**
Windows 11

**Which versions of Node.js / npm are you running?**
`Node.js v17.6.0`
`npm 8.5.1`

### PR DESCRIPTION
**Pull request by rexxars**
### Description

The `open` module tries to use the `SYSTEMROOT` environment variable on Windows, which seems to (sometimes?) not exist. Some backgrounds here: https://github.com/sindresorhus/open/pull/299

Sindre seems unwilling to fix in the `open` module, so I figure we might as well implement a workaround for it since it currently causes issues for onboarding of new users on Windows (the `login` action will fail when attempting to open a browser).

Fixes #4195
Fixes #4194
[sc-30570]

### What to review

- Code looks reasonable (I haven't been able to reproduce/test this on Windows)

### Notes for release

- Fixes an issue where opening a browser from the CLI tool on Windows might crash

### CODE REVIEW

**Review by binoy14 — APPROVED** [review]

File: packages/@sanity/cli/src/cli.ts [hunk 1]
```diff
@@ -240,3 +242,21 @@ function loadAndSetEnvFromDotEnvFiles({workDir, cmd}: {workDir: string; cmd: str
...
   /* eslint-disable no-process-env */
 }
+
+/**
+ * Apparently, Windows environment variables are supposed to be case-insensitive,
+ * (https://nodejs.org/api/process.html#processenv). However, it seems they are not?
+ * `process.env.SYSTEMROOT` is sometimes `undefined`, whereas `process.env.SystemRoot` is _NOT_.
+ *
+ * The `open` npm module uses the former to open a browser on Powershell, and Sindre seems
+ * unwilling to fix it (https://github.com/sindresorhus/open/pull/299#issuecomment-1447587598),
```
Comment (sindresorhus) [inline packages/@sanity/cli/src/cli.ts:252]: That's not what I said. I said I wanted to see an issue posted on Node.js first, so it can be fixed properly eventually. When that's done, I'm happy to merge the workaround.
